company1.name=مفید شیشه
company1.server=155.155.155.230
company1.port=1433
company1.database=Sgdb
company1.username=sa
company1.password=Mofid1359

company2.name=نفیس شیشه
company2.server=155.155.155.168
company2.port=1433
company2.database=nafis
company2.username=sa
company2.password=Mali1359

company3.name=صنایع زاب سان ارومیه
company3.server=155.155.155.172
company3.port=1433
company3.database=zabsan
company3.username=sa
company3.password=Zabsan1359